### ISSUE TITLE
DIGIT Works Comments + Critiques

### ISSUE THREAD

**Issue by rcc5418** [rcc5418/CourtRecord#1]
Post suggestions for our project here, like any changes to the project or the website we could make!

**Comment by lindseyxwood** [comment]
Wow! Your project looks great! I like your Network Visualizations and seeing the most common speakers in Ace Attorney is interesting. My only critique is HTML/CSS related as it is slightly hard to read what is on your page with the translucent boxes.

**Comment by alissongossage** [comment]
I liked how you introduced the game beforehand, so we understand how it works. The XQuery graph is very impressive, and hoepfully you can get the Objection.lol working how you want it!

**Comment by gylertaydos** [comment]
It's so cool that you actually got text generation to work, I'm jealous. As far as critiques or where to take the project, I'm not sure I can say anything you don't already know. It's probably just an issue with your training data (or how you're training it) and thats why the text thats being generated is just a bunch of mumbo-jumbo and combinations of two other characters' names.

**Comment by OH-ThatGuy** [comment]
I've never actually played any of the Ace Attorney games, but the style is so recognizable that I could point it out anywhere easily. I really like how you went to lengths to recreate that unique style on your website, it really helps tie the whole project together. I look forward to seeing this potentially develop further.

**Comment by sammoniot** [comment]
I like the web design, especially the member's page and the SVG. I recommend simplifying the analysis and explaining more about the significance of the findings. There's a lot of text on the page and I think some of it could be either deleted or reduced.
